/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageload;

import static java.awt.AWTEventMulticaster.add;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author Moumi
 */ 
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public String loginname;
     public String newuser;
     public createaccount c;
     public String m;
     public String n;
     public String finalname;
    public File cfile,g;
    public int bounty=0;
    public int endindex;
    public ImageIcon currentimage;
    public int flag=0;
    public int width=1;
    public int height=1;
    public int initialx,initialy,finalx,finaly;
     public Cropclass crop;
     public BufferedImage outputImage;
     public int flag2;
     public String [] list;
     public String uname;
     public String currentstring;
     public String f;
     public int nextback;
     public int index;
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resizemenu = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        percentage = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        pixel = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        Upload = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField4 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Createaccount = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        Received = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        login = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        R = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        Showfiles = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        //DefaultListModel info = new DefaultListModel();
        jList1 = new javax.swing.JList();
        jButton20 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();

        resizemenu.setMinimumSize(new java.awt.Dimension(500, 350));

        jLabel2.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        jLabel2.setText("Enter Your Choice:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jRadioButton1.setText("By Percentage");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jRadioButton2.setText("By Pixel");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resizemenuLayout = new javax.swing.GroupLayout(resizemenu.getContentPane());
        resizemenu.getContentPane().setLayout(resizemenuLayout);
        resizemenuLayout.setHorizontalGroup(
            resizemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resizemenuLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resizemenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        resizemenuLayout.setVerticalGroup(
            resizemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resizemenuLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(resizemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        percentage.setMinimumSize(new java.awt.Dimension(450, 270));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Enter Percentage:");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setText("%");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout percentageLayout = new javax.swing.GroupLayout(percentage.getContentPane());
        percentage.getContentPane().setLayout(percentageLayout);
        percentageLayout.setHorizontalGroup(
            percentageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(percentageLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, percentageLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        percentageLayout.setVerticalGroup(
            percentageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(percentageLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addGroup(percentageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pixel.setMinimumSize(new java.awt.Dimension(450, 270));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("Width:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setText("Height:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton6.setText("Done!");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pixelLayout = new javax.swing.GroupLayout(pixel.getContentPane());
        pixel.getContentPane().setLayout(pixelLayout);
        pixelLayout.setHorizontalGroup(
            pixelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pixelLayout.createSequentialGroup()
                .addGroup(pixelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pixelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(pixelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(68, 68, 68)
                        .addGroup(pixelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jTextField2)))
                    .addGroup(pixelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton6)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        pixelLayout.setVerticalGroup(
            pixelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pixelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(pixelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pixelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton6)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        Upload.setMinimumSize(new java.awt.Dimension(450, 350));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Enter Name:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Enter Password");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton12.setText("Done!");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton14.setText("Create New Account");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("OR:");

        javax.swing.GroupLayout UploadLayout = new javax.swing.GroupLayout(Upload.getContentPane());
        Upload.getContentPane().setLayout(UploadLayout);
        UploadLayout.setHorizontalGroup(
            UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UploadLayout.createSequentialGroup()
                .addGroup(UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UploadLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4)
                            .addComponent(jPasswordField1)))
                    .addGroup(UploadLayout.createSequentialGroup()
                        .addGroup(UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UploadLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jButton12))
                            .addGroup(UploadLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jButton14))
                            .addGroup(UploadLayout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jLabel15)))
                        .addGap(0, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        UploadLayout.setVerticalGroup(
            UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UploadLayout.createSequentialGroup()
                .addGroup(UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UploadLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8))
                    .addGroup(UploadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(UploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        Createaccount.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel10.setText("Enter Name:");

        jLabel11.setText("Enter Password:");

        jButton15.setText("Create new account");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreateaccountLayout = new javax.swing.GroupLayout(Createaccount.getContentPane());
        Createaccount.getContentPane().setLayout(CreateaccountLayout);
        CreateaccountLayout.setHorizontalGroup(
            CreateaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateaccountLayout.createSequentialGroup()
                .addGroup(CreateaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateaccountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CreateaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CreateaccountLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(30, 30, 30)
                                .addComponent(jTextField5))
                            .addGroup(CreateaccountLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CreateaccountLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton15)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        CreateaccountLayout.setVerticalGroup(
            CreateaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateaccountLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(CreateaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(CreateaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jButton15)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        Received.setMinimumSize(new java.awt.Dimension(250, 150));

        jLabel12.setText("Account has been created");

        jButton16.setText("OK");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReceivedLayout = new javax.swing.GroupLayout(Received.getContentPane());
        Received.getContentPane().setLayout(ReceivedLayout);
        ReceivedLayout.setHorizontalGroup(
            ReceivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReceivedLayout.createSequentialGroup()
                .addGroup(ReceivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReceivedLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel12))
                    .addGroup(ReceivedLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton16)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        ReceivedLayout.setVerticalGroup(
            ReceivedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReceivedLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jButton16)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        login.setMinimumSize(new java.awt.Dimension(400, 200));

        jLabel13.setText("jLabel13");

        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login.getContentPane());
        login.getContentPane().setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel13)
                .addGap(35, 35, 35)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        R.setMinimumSize(new java.awt.Dimension(150, 150));

        jLabel14.setText("jLabel14");

        jButton18.setText("Finish");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RLayout = new javax.swing.GroupLayout(R.getContentPane());
        R.getContentPane().setLayout(RLayout);
        RLayout.setHorizontalGroup(
            RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jButton18))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        RLayout.setVerticalGroup(
            RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jButton18)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        Showfiles.setMinimumSize(new java.awt.Dimension(600, 500));

        jLabel16.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jLabel16.setText("jLabel16");

        jLabel17.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel17.setText("NO of files in your account:");

        jLabel18.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel18.setText("Choose to download:");

        jLabel19.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel19.setText("jLabel19");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(300, 200));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 200));

        jList1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            //List1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() {return list.length; }
            public Object getElementAt(int i) { return list[i]; }
        });
        jList1.setMaximumSize(new java.awt.Dimension(300, 200));
        jList1.setMinimumSize(new java.awt.Dimension(300, 200));
        jList1.setPreferredSize(new java.awt.Dimension(300, 200));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jButton20.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jButton20.setText("Download");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel20.setText("jLabel20");

        javax.swing.GroupLayout ShowfilesLayout = new javax.swing.GroupLayout(Showfiles.getContentPane());
        Showfiles.getContentPane().setLayout(ShowfilesLayout);
        ShowfilesLayout.setHorizontalGroup(
            ShowfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowfilesLayout.createSequentialGroup()
                .addGroup(ShowfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShowfilesLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ShowfilesLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel17)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel19))
                    .addGroup(ShowfilesLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel18))
                    .addGroup(ShowfilesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ShowfilesLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButton20))
                    .addGroup(ShowfilesLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel20)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        ShowfilesLayout.setVerticalGroup(
            ShowfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowfilesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(ShowfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ShowfilesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel19)))
                .addGap(27, 27, 27)
                .addComponent(jLabel18)
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton20)
                .addGap(35, 35, 35))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageload/start3.jpg"))); // NOI18N
        jButton2.setText("start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageload/cover3.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, "card5");

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 600));

        jButton1.setBackground(new java.awt.Color(102, 102, 0));
        jButton1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jButton4.setText("Rotate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jButton5.setText("Resize");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 255, 153));
        jButton7.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jButton7.setText("Crop");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 102, 0));
        jButton8.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jButton8.setText("Done!");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 102, 255));
        jButton9.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jButton9.setText("Save");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(102, 255, 51));
        jButton10.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jButton10.setText("Open");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 153, 0));
        jButton11.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jButton11.setText("Upload");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 153, 0));
        jButton13.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jButton13.setText("Delete");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 51, 51));
        jButton19.setText("ACCESS ACCOUNT");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton11)
                        .addGap(53, 53, 53)
                        .addComponent(jButton13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(35, 35, 35)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton19)))
                .addContainerGap(481, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton19))
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel1, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        jPanel2.setVisible(false);
            jPanel1.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed
    int count=0;
    
   public  String[] createarray(File f)
    {
        String[] filename;
       // FilenameFilter filefilter;
    filename=f.getParentFile().list();
    String[] newarray=new String[filename.length] ;
    int k=0,i;
    
    for( i=0;i<filename.length;i++)
    {
    
        
        int index=filename[i].lastIndexOf('.');
        if(index>0&&index<filename[i].length()-1)
        {
            String m=filename[i].substring(index+1);
           if(m.equalsIgnoreCase("jpg")||m.equalsIgnoreCase("bmp")||m.equalsIgnoreCase("png")||m.equalsIgnoreCase("gif"))
           {
               newarray[k]= new String(filename[i]);
               
               k++;
           }
               
        }
     }
    
    endindex=k;
        System.out.println(endindex);
    return newarray;
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(nextback==0){
        int p;
        bounty=0;
        
        String[] finalarray=createarray(cfile);
        ImageIcon[] imagelist=new ImageIcon[endindex];
        //for(int y=0;y<endindex;y++)
        //System.out.println(finalarray[y]);
        for( p=0;p<endindex;p++){
           String s=cfile.getParentFile().getAbsolutePath()+"\\"+finalarray[p];
           if(cfile.getAbsolutePath().equalsIgnoreCase(s))count=p;
            System.out.println(p+s);
            g=new File(s);
            URI uri=g.toURI();
            try {
                imagelist[p] = new ImageIcon(uri.toURL());
                //System.out.println(uri.toURL()+finalarray[p]);
            } catch (MalformedURLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       if(count<endindex-1) 
       {
           currentimage=imagelist[++count];
           
           //count++;
       }
       else if(count==endindex-1)
       {
           count=0;
           currentimage=imagelist[count];
       }
       String s=cfile.getParentFile().getAbsolutePath()+"\\"+finalarray[count];
           cfile=new File(s);
           try {
            currentimage=resize(cfile,514,384);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           jLabel1.setIcon(currentimage);
       jLabel1.setVisible(true);
        try {
            outputImage=ImageIO.read(cfile);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(nextback==1)
        {
             if(index<list.length-1) 
       {
           //currentimage=imagelist[++count];
           f=list[++index];
           System.out.println(index + " "+ f);
           String m=finalname.concat("/");
        currentstring=m.concat(f);
          c=new createaccount();
                 try {
                     c.download("download".concat(currentstring),f);
                 } catch (IOException ex) {
                     Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                 }
            //System.out.println(f);
            Showfiles.setVisible(false);
            login.setVisible(false);
            /*File cfile=new File("folder",f);
            
          URI uri= cfile.toURI();
                 try {
                     currentimage=new ImageIcon(uri.toURL());
                     jLabel1.setIcon(currentimage);
                 } catch (MalformedURLException ex) {
                     Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                 }
           //jLabel1.setIcon(currentimage);
                 //File f=j.getSelectedFile();
        try {
            File g=new File("folder",f);
            currentimage=resize(g,514,384);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        cfile=new File(g.getAbsolutePath());
        try {
            outputImage=ImageIO.read(cfile);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //URI s=g.toURI();
       
        // MF m=new MF();
        
        jLabel1.setIcon(currentimage);*/
             cfile=new File("folder",f);
        try {
            currentimage=resize(cfile,514,384);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           jLabel1.setIcon(currentimage);
       jLabel1.setVisible(true);
       try {
            outputImage=ImageIO.read(cfile);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
           //count++;
       }
       else if(index==list.length-1)
       {
           index=1;
           f=list[index];
              System.out.println(index +" "+ f);
           String m=finalname.concat("/");
           currentstring=m.concat(f);
          c=new createaccount();
                 try {
                     c.download("download".concat(currentstring),f);
                 } catch (IOException ex) {
                     Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                 }
            //System.out.println(f);
            Showfiles.setVisible(false);
            login.setVisible(false);
           /* cfile=new File("folder",f);
            
          URI uri= cfile.toURI();
                 try {
                     currentimage=new ImageIcon(uri.toURL());
                     jLabel1.setIcon(currentimage);
                 } catch (MalformedURLException ex) {
                     Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                 }
           //currentimage=imagelist[count];
             try {
            File g=new File("folder",f);
            currentimage=resize(g,514,384);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        cfile=new File(g.getAbsolutePath());
        try {
            outputImage=ImageIO.read(cfile);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //URI s=g.toURI();
       
        // MF m=new MF();
        
        jLabel1.setIcon(currentimage);*/
             cfile=new File("folder",f);
        try {
            currentimage=resize(cfile,514,384);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           jLabel1.setIcon(currentimage);
       jLabel1.setVisible(true);
       try {
            outputImage=ImageIO.read(cfile);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
       }
        }
        
       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(nextback==0){
        int p;
        bounty=0;
        
         String[] finalarray=createarray(cfile);
        ImageIcon[] imagelist=new ImageIcon[endindex];
        
        for( p=0;p<endindex;p++){
           String s=cfile.getParentFile().getAbsolutePath()+"\\"+finalarray[p];
           if(cfile.getAbsolutePath().equalsIgnoreCase(s))count=p;
            System.out.println(p+s);
            g=new File(s);
            URI uri=g.toURI();
            try {
                imagelist[p] = new ImageIcon(uri.toURL());
                //System.out.println(uri.toURL()+finalarray[p]);
            } catch (MalformedURLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
       //if(count==endindex)count-=2;
       if(count<endindex && count>0) 
       {
           currentimage=imagelist[--count];
           
           //count--;
        }
       else if(count==0)
       {
           count=endindex-1;
           currentimage=imagelist[count];
       }
       String s=cfile.getParentFile().getAbsolutePath()+"\\"+finalarray[count];
            cfile=new File(s);
        try {
            currentimage=resize(cfile,514,384);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           jLabel1.setIcon(currentimage);
       jLabel1.setVisible(true);
       try {
            outputImage=ImageIO.read(cfile);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
        else if(nextback==1){
            
    
        if(index<=list.length-1 && index>1) 
       {
           //currentimage=imagelist[++count];
           f=list[--index];
           System.out.println(index + " "+ f);
           String m=finalname.concat("/");
        currentstring=m.concat(f);
          c=new createaccount();
                 try {
                     c.download("download".concat(currentstring),f);
                 } catch (IOException ex) {
                     Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                 }
            //System.out.println(f);
            Showfiles.setVisible(false);
            login.setVisible(false);
             //File g=new File("folder",f);
            //File f=j.getSelectedFile();
       
           /* cfile=new File("folder",f);
           URI uri= cfile.toURI();
                 try {
                     currentimage=new ImageIcon(uri.toURL());
                     jLabel1.setIcon(currentimage);
                 } catch (MalformedURLException ex) {
                     Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                 }
           //jLabel1.setIcon(currentimage);*/
             /*try {
            File g=new File("folder",f);
            currentimage=resize(g,514,384);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        cfile=new File(g.getAbsolutePath());
        try {
            outputImage=ImageIO.read(cfile);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //URI s=g.toURI();
       
        // MF m=new MF();
        
        jLabel1.setIcon(currentimage);*/
                 
             cfile=new File("folder",f);
        try {
            currentimage=resize(cfile,514,384);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           jLabel1.setIcon(currentimage);
       jLabel1.setVisible(true);
       try {
            outputImage=ImageIO.read(cfile);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
           //count++;
       }
       else if(index==1)
       {
           index=list.length-1;
           f=list[index];
              System.out.println(index +" "+ f);
           String m=finalname.concat("/");
           currentstring=m.concat(f);
          c=new createaccount();
                 try {
                     c.download("download".concat(currentstring),f);
                 } catch (IOException ex) {
                     Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                 }
            //System.out.println(f);
            Showfiles.setVisible(false);
            login.setVisible(false);
             //File g=new File("folder",f);
            
            /*cfile=new File("folder",f);
           URI uri= cfile.toURI();
                 try {
                     currentimage=new ImageIcon(uri.toURL());
                     jLabel1.setIcon(currentimage);
                 } catch (MalformedURLException ex) {
                     Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                 }
           //currentimage=imagelist[count];
             try {
            File g=new File("folder",f);
            currentimage=resize(g,514,384);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        cfile=new File(g.getAbsolutePath());
        try {
            outputImage=ImageIO.read(cfile);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //URI s=g.toURI();
       
        // MF m=new MF();
        
        jLabel1.setIcon(currentimage);*/
             cfile=new File("folder",f);
        try {
            currentimage=resize(cfile,514,384);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           jLabel1.setIcon(currentimage);
       jLabel1.setVisible(true);
       try {
            outputImage=ImageIO.read(cfile);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
       }
        }
    
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jLabel1.setVisible(false);
        bounty++;
        MyFrame m=new MyFrame(currentimage,bounty);
        m.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    public  ImageIcon resize(File c,int scaledWidth, int scaledHeight)
            throws IOException {
        // reads input image
        //File inputFile = new File(inputImagePath);
        BufferedImage inputImage = ImageIO.read(c);
 
        // creates output image
        outputImage = new BufferedImage(scaledWidth,
                scaledHeight, inputImage.getType());
 
        // scales the input image to the output image
        Graphics2D g2d = outputImage.createGraphics();
        g2d.drawImage(inputImage, 0, 0, scaledWidth, scaledHeight, null);
        g2d.dispose();
        Image pimage=Toolkit.getDefaultToolkit().createImage(outputImage.getSource());
        ImageIcon m=new ImageIcon(pimage);
        //System.out.println(m.getDescription());
        //jLabel1.setIcon(m);
       return m;
       
    }
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    
       resizemenu.setLocationRelativeTo(null);
        resizemenu.setVisible(true);
       
    }//GEN-LAST:event_jButton5ActionPerformed
  public ImageIcon resize(File f,double percent) throws IOException {
        //File inputFile = new File(inputImagePath);
        BufferedImage inputImage = ImageIO.read(f);
        int scaledWidth = (int) (inputImage.getWidth() * percent);
        int scaledHeight = (int) (inputImage.getHeight() * percent);
        ImageIcon m=resize(f,scaledWidth, scaledHeight);
        return m;
    }
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        pixel.setVisible(false);
        percentage.setLocationRelativeTo(null);
        percentage.setVisible(true);
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String s=jTextField1.getText();
        //System.out.println(s);
        double value = Double.parseDouble(s);
        value=value/100;
        System.out.println(s);
        try {
            ImageIcon m=resize(cfile,value);
            percentage.setVisible(false);
            resizemenu.setVisible(false);
            jLabel1.setIcon(m);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        percentage.setVisible(false);
        pixel.setLocationRelativeTo(null);
        pixel.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        String s=jTextField2.getText();
        width = Integer.parseInt(s);
        //System.out.println(s);
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
         String s=jTextField3.getText();
        //System.out.println(s);
          height = Integer.parseInt(s);
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        pixel.setVisible(false);
        resizemenu.setVisible(false);
        try {
            ImageIcon m=resize(cfile,width,height);
            jLabel1.setIcon(m);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed
   public ImageIcon croppedimage(File f,int ix,int iy,int fx,int fy,ImageIcon cimage) throws IOException
   {
       
        BufferedImage buffImg = new BufferedImage(cimage.getIconWidth(),cimage.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
        buffImg=ImageIO.read(f);
        BufferedImage buffImg2 = buffImg.getSubimage(ix,iy,fx,fy); //fill in the corners of the desired crop location here
        BufferedImage buffImg3 = new BufferedImage(buffImg2.getWidth(), buffImg2.getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics g = buffImg3.createGraphics();
         g.drawImage(buffImg2, 0, 0, null);
         g.dispose();
        Image pimage=Toolkit.getDefaultToolkit().createImage(buffImg3.getSource());
        ImageIcon m=new ImageIcon(pimage);
        return m;
   }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
        try {
            
            crop = new Cropclass(outputImage,currentimage);
             jLabel1.addMouseListener((MouseListener) crop);
        jLabel1.addMouseMotionListener((MouseMotionListener) crop);
        //ImageIcon m=crop.getimage();
        //jLabel1.setIcon(m);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ImageIcon m=crop.getimage();
        jLabel1.setIcon(m);
        outputImage=crop.getbuffer();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        //File f=new File("C:\\Users\\Lt.Col Shams\\Desktop\\hello.jpg");
        JFileChooser j=new JFileChooser();
        j.showSaveDialog(null);
         //j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
         File saveFile=new File(cfile.getName());
         j.setSelectedFile(saveFile);
             int rval = j.showSaveDialog(null);
             if (rval == JFileChooser.APPROVE_OPTION) {
                 saveFile = j.getSelectedFile();
                 try {
                     ImageIO.write(outputImage, "jpg", saveFile);
                 } catch (IOException ex) {
                 }
             }
        
    }//GEN-LAST:event_jButton9ActionPerformed
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        nextback=0;
        JFileChooser j=new JFileChooser();
        j.showOpenDialog(null);
        
        File f=j.getSelectedFile();
        try {
            currentimage=resize(f,514,384);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        cfile=new File(f.getAbsolutePath());
        try {
            outputImage=ImageIO.read(cfile);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        URI s=f.toURI();
       
        // MF m=new MF();
        
        jLabel1.setIcon(currentimage);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        if(cfile.delete()){
            System.out.println("deleted");
            jLabel1.setIcon(null);
        }
        else System.out.println("not deleted");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
  // TODO add your handling code here:
        String s=new String(jPasswordField1.getPassword());
        uname=jTextField4.getText();
        loginname=jTextField4.getText().concat(s);
        finalname=loginname;
        loginname="login".concat(loginname);
        createaccount d=new createaccount();
        Upload.setVisible(false);
        try {
            n=d.send(loginname);
             //login.setVisible(true);
            
                //login.setVisible(true);
                jLabel13.setText(n);
                jButton17.setVisible(false);
                login.setLocationRelativeTo(null);
            login.setVisible(true);
            if(n.equals("Logged In Succesfully!!!"))
            {
                //login.setVisible(true);
                if(flag2==1) jButton17.setText("Send this file");
                else if(flag2==2) jButton17.setText("View your account");
               jButton17.setVisible(true);
                
            }
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
          Createaccount.setVisible(false);
        newuser=jTextField5.getText().concat(jTextField6.getText());
        newuser="newuser".concat(newuser);
        //System.out.println(newuser);
        //Createaccount.setVisible(false);
        //Acceptaccount a=new Acceptaccount();
       // Acceptaccount.accept();
        
        try {
            //String m;
            //createaccount c=new createaccount();
           // if(m.equals("confirmed")){
           createaccount c=new createaccount();
            m=c.send(newuser);
            //Createaccount.setVisible(false);
            Received.setLocationRelativeTo(null);
            Received.setVisible(true);
            jLabel12.setText(m);
            
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        Received.setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
         c=new createaccount();
         login.setVisible(false);
        try {
            
            if(jButton17.getText().equals("Send this file")){
            String x= c.sendfile(cfile, finalname);
            R.setLocationRelativeTo(null);
            R.setVisible(true);
           jLabel14.setText(x);
            }
            if(jButton17.getText().equals("View your account")){
                
           list=c.view("viewing".concat(finalname));
           DefaultListModel d=new DefaultListModel();
           
           for(int i=0;i<list.length;i++)
           {
              d.addElement(list[i]);
               System.out.println(i+" "+ list[i]);
           }
            jList1.setModel(d);
            Showfiles.setVisible(true);
            jButton20.setEnabled(true);
            jLabel16.setText("Account name: ".concat(uname));
            jLabel17.setText("No of files in your account: ");
            jLabel19.setText(Integer.toString((list.length-1)));
            jLabel20.setVisible(false);
            jScrollPane2.setVisible(true);
            
            jList1.setVisible(true);
            jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
               // jList1ValueChanged(null);
            }
            
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        flag2=1;
        Upload.setLocationRelativeTo(null);
         jTextField4.addActionListener(new ActionListener()
        {

            @Override
            public void actionPerformed(ActionEvent ae) {
               jTextField4.transferFocus();
         // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
                    
          });
        Upload.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
       // login.setVisible(false);
        R.setVisible(false);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        Upload.setVisible(false);
        Createaccount.setLocationRelativeTo(null);
         jTextField5.addActionListener(new ActionListener()
        {

            @Override
            public void actionPerformed(ActionEvent ae) {
               jTextField5.transferFocus();
         // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
                    
          });
        Createaccount.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        flag2=2;
        Upload.setLocationRelativeTo(null);
         jTextField4.addActionListener(new ActionListener()
        {

            @Override
            public void actionPerformed(ActionEvent ae) {
               jTextField4.transferFocus();
         // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
                    
          });
        Upload.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        //jList1.setSelectionModel();
       /* f=jList1.getSelectedValue().toString();
        for (int i=0;i<list.length;i++) {
        if (list[i].equals(f)) {
          index = i;
          System.out.println(index);
         break;
    }
        }
        String m=finalname.concat("/");
        currentstring=m.concat(f);
        //System.out.println(f);*/
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        //jButton1.setVisible(false);
        //jButton3.setText("logout");
        if(list.length-1==0) 
        {
            jButton20.setEnabled(false);
            jLabel20.setText("Nothing to download!!!");
            jLabel20.setVisible(true);
        }
        else{
       nextback=1;
       
        c=new createaccount();
         f=jList1.getSelectedValue().toString();
        for (int i=0;i<list.length;i++) {
        if (list[i].equals(f)) {
          index = i;
          System.out.println(index);
         break;
    }
        }
        String m=finalname.concat("/");
        currentstring=m.concat(f);
        
            try {
                c.download("download".concat(currentstring),f);
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            //System.out.println(f);
            Showfiles.setVisible(false);
            login.setVisible(false);
             cfile=new File("folder",f);
        try {
            currentimage=resize(cfile,514,384);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           jLabel1.setIcon(currentimage);
       jLabel1.setVisible(true);
       try {
            outputImage=ImageIO.read(cfile);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_jButton20ActionPerformed
 
    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
       
    }//GEN-LAST:event_jTextField4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame n=new NewJFrame();
                n.setLocationRelativeTo(null);
                n.setVisible(true);
                 //MF m=new MF();
            }
        });
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Createaccount;
    private javax.swing.JDialog R;
    private javax.swing.JDialog Received;
    private javax.swing.JDialog Showfiles;
    private javax.swing.JDialog Upload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JDialog login;
    private javax.swing.JDialog percentage;
    private javax.swing.JDialog pixel;
    private javax.swing.JDialog resizemenu;
    // End of variables declaration//GEN-END:variables
}
